# Generated by Django 3.2 on 2022-02-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logistics', '0002_historicalroutes_routes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalroutes',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Ruta'},
        ),
        migrations.AlterModelOptions(
            name='historicaltransaction',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Transaccion'},
        ),
        migrations.AlterModelOptions(
            name='historicaltransfer_details',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Detalle de Transferencia'},
        ),
        migrations.AlterModelOptions(
            name='historicaltrasport',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Transporte'},
        ),
        migrations.AlterModelOptions(
            name='routes',
            options={'ordering': ('Name_Route',), 'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaccion', 'verbose_name_plural': 'Transacciones'},
        ),
        migrations.AlterModelOptions(
            name='transfer_details',
            options={'ordering': ['created_at'], 'verbose_name': 'Detalle de Transferencia', 'verbose_name_plural': 'Detalles de Transferencia'},
        ),
        migrations.AlterModelOptions(
            name='trasport',
            options={'ordering': ['created_at'], 'verbose_name': 'Transporte', 'verbose_name_plural': 'Transportes'},
        ),
    ]
