# Generated by Django 3.2 on 2022-02-14 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ('first_name',), 'verbose_name': 'Empleados', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='historicalemployees',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Empleados'},
        ),
        migrations.RemoveField(
            model_name='employees',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalemployees',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalemployees',
            name='updated_at',
        ),
    ]
