# Generated by Django 3.2 on 2022-02-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='Descriptions',
            field=models.CharField(blank=True, max_length=500, verbose_name='Descriptión'),
        ),
        migrations.AddField(
            model_name='product',
            name='Models',
            field=models.CharField(default='Modelo', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='Type',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Tablet', 'Tablet'), ('Accessory', 'Accessory'), ('Printer', 'Printer'), ('Scanner', 'Scanner'), ('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Monitor', 'Monitor'), ('Software', 'Software'), ('Other', 'Other')], default='Tipo', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Producto', max_length=50),
        ),
        migrations.DeleteModel(
            name='HistoricalProduct',
        ),
    ]
