# Generated by Django 3.2 on 2022-02-14 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0002_auto_20220213_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(default='Producto', max_length=50)),
                ('Models', models.CharField(default='Modelo', max_length=100)),
                ('Serial', models.CharField(db_index=True, max_length=50)),
                ('IMEI', models.CharField(db_index=True, max_length=50)),
                ('Descriptions', models.CharField(blank=True, max_length=500, verbose_name='Descriptión')),
                ('Type', models.CharField(choices=[('Phone', 'Phone'), ('Tablet', 'Tablet'), ('Accessory', 'Accessory'), ('Printer', 'Printer'), ('Scanner', 'Scanner'), ('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Monitor', 'Monitor'), ('Software', 'Software'), ('Other', 'Other')], default='Tipo', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Productos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
