# Generated by Django 3.2 on 2022-02-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_assigned_historicalassigned_historicalinventory_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
